Repository ReactiveX/RxGo, pull requests merged in 2018-12, with the labels that each got.

#100 starting developer RxGo version 2
  README.md
Labels: version 2

#95 Major refactoring & new operators
  README.md
  connectable/connectable.go
  connectable/connectable_test.go
  connectableobservable.go
  connectableobservable_test.go
  create.go
  create_test.go
  disposable.go
  errors/errors.go
  eventhandler.go
  examples/flatmap/flatmap_slice.go
  examples/flatmap/flatmap_slice_test.go
  examples/reactive_sum/sum.go
  examples/scroll/server.go
  flatmap.go
  flatmap_test.go
  fx/fx.go
  handlers/handlers.go
  handlers/handlers_test.go
  iterable/iterable_test.go
  iterator.go
  observable.go
  observable/observable.go
  observable/options.go
  observable/options_test.go
  observable_test.go
  observer.go
  observer/observer.go
  observer_mock.go
  observer_test.go
  optional/optional.go
  optional/optional_test.go
  options/options.go
  options/options_test.go
  single.go
  single_test.go
  singleobserver.go
  subscription/subscription.go
  subscription/subscription_test.go
Labels: version 2

#116 fixed travis image status to v2
  README.md
Labels: help wanted, version 2

#117 Math operators: Average, Concat, Min and Max
  assert.go
  assert_test.go
  fx.go
  observable.go
  observable_test.go
  observablecreate.go
  observablecreate_test.go
  single.go
Labels: feature, version 2

#155 Sum operator
  observable.go
  observable_test.go
Labels: feature, version 2

#157 StartWith operator
  assert.go
  assert_test.go
  iterable/iterable_test.go
  observable.go
  observable_test.go
Labels: feature, version 2
